version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: C2p7/59&70>;>a\#5lHoX5uS,LVK\o*~2&2h5Y.D
      POSTGRES_DB: boss-nation
